### ISSUE TITLE
Ensure sufficient number of phase realizations in PS

### ISSUE THREAD

**Issue by H0R5E** [SNL-WaterPower/WecOptTool-MATLAB#56]
> We use multiple realizations to deal with phase-dependent nature of a nonlinear model. Since the pseudo spectral results are nonlinear, they are dependent on the phasing of the waves. Thus, we average over 5 realizations - this was previously found to be sufficient, but I think it warrants another look just to make sure. I believe we also considered using a while loop and looking for convergence...

_Originally posted by @ryancoe in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjQ1MjI5MTYzOnYy/pull_request_review_threads/more_comments_

**Comment by ssolson** [comment]
@ryancoe on your WaveBot branch for [WaveBot Case B](https://github.com/ryancoe/WecOptTool/blob/waveBot/WaveBot_caseB.m ) you plot the power returned from the method `simPerformance` which is part of the  `WaveBot` class.
 
This `simPerformance` method returns the power of the first phase realization:
https://github.com/ryancoe/WecOptTool/blob/waveBot/toolbox/%2BWecOptLib/%2Bmodels/%40WaveBot/WaveBot.m#L334-L348

However, looking at this discussion it seems we should be doing an averaging over each phase realization. As I look to incorporate WaveBot Case B into the current structure how should I proceed?

**Comment by ryancoe** [comment]
Yes, this is an interesting subtlety.
 - **First phase realization:** I chose to present the first realization from `PS` when showing the frequency or time domain results, since the phase angle for this first case matches the `CC` and `P` cases. Averaging in this case would be either incorrect (time domain) or at least confusing/misleading (frequency domain).
 - **All phase realizations:** When showing an average or a maximum from `PS`, I use all of the phasings.

Happy to discuss more via phone if you like.

**Comment by H0R5E** [comment]
OK, so I think there are two things going on here that could be better (I believe). These are my thoughts:

1. The use of random phases for the CC and P controllers is unnecessary, with the only outcome being to shift the time domain results. If they are necessary, then it's not clear why.
2. The phase realizations used in the PS calculation should be integrated. What we have at the moment is an ad-hoc [Monte Carlo integration](https://en.wikipedia.org/wiki/Monte_Carlo_integration) scheme, which I think should be formalised a bit more. You can use the MATLAB [integral command](https://uk.mathworks.com/help/matlab/ref/integral.html), but it's extremely slow when solving per frequency (it's more efficient for an aggregated value, but that's probably not what we want).

I haven't really been able to dig out any mathematical background for the use of random phases as we have it right now, so if you have something I could look at, that would be helpful.

I also think this relates to inner optimization in the PS controller. If integration is the correct way to go, then perhaps having one optimisation loop rather than two may help with the efficiency losses.

@ryancoe, does this make sense to you?

**Comment by ryancoe** [comment]
1. Yes, you're right about this. Because the `CC` and `P` controllers rely on linear analyses (frequency domain), phasing is immaterial to the results. Nonetheless, I do find the time realizations that can plot somewhat helpful for intuitive understanding. Perhaps we should put a note somewhere about this?
2. Not sure if I agree with you on this one... but it may be that I'm missing something. The diagram below illustrates my understanding of what we want to do. Since the results for `PS` are phase-dependent, we need to take the average over `n_ph` phasings. Currently, we have [hardcoded `n_ph=5`](https://github.com/SNL-WaterPower/WecOptTool/blob/05c2e5c601e77659a623b5b76251d233f4d07098/examples/WaveBot/simulateDevice.m#L228), but it would be better to monitor _how much the average changes with each additional phase realizations_ and continue or stop the analysis based on this. I think there are probably establish (and perhaps existing MATLAB functions) for checking asymptotic convergence, but I think it should go something like: 

```matlab
while change_in_avg > threshold && idx_ph < my_limit
   results(idx_ph) = simulate(..) % get results for this phasing
   avg(idx_ph) = mean([avg(idx_ph - 1)*(idx_ph - 1), results(idx_ph)]); % update the average
   change_in_avg = (avg(idx_ph) - avg(idx_ph-1))/avg(idx_ph-1) % fractional change in average
   idx_ph = idx_ph;
end
```

![Untitled](https://user-images.githubusercontent.com/5589887/98016176-e51df380-1dba-11eb-9dd8-2ae3ff486ffa.png)

**Comment by H0R5E** [comment]
> 2\. how much the average changes with each additional phase realizations

So, the argument for this being an integral is simply that the more phase realizations you add, the more accurate is the solution. Thus, as the number of phase realisations tends to infinity, the true result is the integral over the phase divided by 2pi. Your approach is therefore an approximation to this integral. 

<img src="https://render.githubusercontent.com/render/math?math=\lim_{n\to\infty}\frac{1}{n}\sum^{n}_{i=1}f(a %2B i\Delta x) = \frac{\int^b_a f(x)dx}{b-a}"> where <img src="https://render.githubusercontent.com/render/math?math=\Delta x=\frac{b-a}{n}">

**Comment by H0R5E** [comment]
I'm also doubling back on what I said about the phases for the CC and P controllers. For a random sea state it _does make a difference_ which phases you simulate _for variables other than the average power_. Here are the results from wavebot with all zero phase, all pi / 2 phase and a set of random phases (from 0 to 2pi):

![phases](https://user-images.githubusercontent.com/5088535/98126224-3d352280-1ead-11eb-98e0-e01a85b08d44.png)

```
         AvgPow    |MaxPow|     PowTHD_dBc    MaxPos    MaxVel      MaxPTO  
          ______    _________    __________    ______    ______    __________

  rand    -90249    2.002e+07       NaN        50.733    33.137    1.1821e+06
 zeros    -90249    2.297e+07       NaN        51.371    40.337    1.1929e+06
 pi / 2   -90249    2.6408e+07      NaN        56.588    34.848    1.3042e+06
```

So, it seems like there may be an optimal set of phases for whichever metric you are interested in. What was also strange is that, for WaveBot and RM3, the phases were only tested over the interval [0, 1] rather than [0, 2pi].
